services:
  laravel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-backend
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8000:8000
    networks:
      - laravel-network
    depends_on:
      - mysql
    command: >
      sh -c "
        composer install &&
        cp .env.example .env &&
        sed -i 's#DB_CONNECTION=.*#DB_CONNECTION=mysql#' .env &&
        sed -i 's#DB_HOST=.*#DB_HOST=mysql#' .env &&
        sed -i 's#DB_PORT=.*#DB_PORT=3306#' .env &&
        sed -i 's#DB_DATABASE=.*#DB_DATABASE=laravel#' .env &&
        sed -i 's#DB_USERNAME=.*#DB_USERNAME=laravel#' .env &&
        sed -i 's#DB_PASSWORD=.*#DB_PASSWORD=laravel#' .env &&
        sed -i 's#SESSION_DRIVER=.*#SESSION_DRIVER=file#' .env &&
        echo 'PAYMENT_API_URL=eksterni_api_iz_wunder_mobility' >> .env &&
        php artisan key:generate &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
